### ISSUE TITLE
configurable outputs formats - zip, sqlite, more...

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#15]
We need to export data into a zip, sqlite, other rel db, etc... if requested

## Acceptance criteria 

* [ ] Able to get zip/sqlite after executing pipelines 

## Tasks

* [ ] edit source spec generator

## Analysis 

```yaml=
meta:
  owner: <owner username>
  ownerid: <owner unique id>
  dataset: <dataset name>
  version: 1
  findability: <published/unlisted/private>
inputs:
  -  # only one input is supported atm
    kind: datapackage
    url: <datapackage-url>
    parameters:
      resource-mapping:
        <resource-name-or-path>: <resource-url>
outputs: // backend has some rule about what is auto-added for you e.g. csv and json is always there for tabular input
  -
    kind: csv 
  -
    kind: json
    resources: '2017-data'
  -
    kind: rdbms
    parameters:
      engine: <pointer to ...>
  -
    kind: sqlite
  -
    kind: npm
    parameters:
      credentials: <pointer to ...>
```

We will have new kinds in specstore (let's say only sqlite for now) that will be provided by CLI. As I understand I must iterate over outputs property and append to current pipeline if there is new kind Eg

```python=
# pipeline-spec
meta:
  ...
inputs:
  - 
    kind: datapackage
    ...
outputs: 
  -
    kind: sqlite

# generator.py in assambler
pipeline = [current_pipeline]
for output in outputs:
    if output[kind] == 'sqlite':
          pipeline.append({run: dump.to_sql, parameters: {engine: lsqlite:///}}})
    etc..
```
yield pipeline_id, {pipeline: pipeline}

Questions:

* configurable or automatic? 
  * should this be passed by cli or hardcoded in pipeline generator?
