### ISSUE TITLE
Pipelines are generated according to old/cached source-spec

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#35]
I Have pushed a new source spec for one of the core datasets using specstore API. 
* API responds with `success=true`
* manually checked database and new spec is there
* Assembler sees that something changed in DB and triggers the planner
* However dashboard shows the "old"  source-spec and pipelines are run according to that
* Result: No changes to my dataset

## Acceptance Criteria

* [x] pipelines are run according to newest source-spec pushed

## Analysis

The source spec I pushed (and currently in DB):

```
meta:
  dataset: finance-vix
  findability: published
  owner: core
  ownerid: core
  version: 2
inputs:
- kind: datapackage
  parameters:
    resource-mapping:
      vix-daily: http://www.cboe.com/publish/ScheduledTask/MktData/datahouse/vixcurrent.csv
  url: https://raw.githubusercontent.com/datasets/finance-vix/master/.datahub/datapackage.json
processing:
  -
    input: vix-daily
    tabulator:
      skip_rows: 2
      headers:
        - Date
        - VIXOpen
        - VIXHigh
        - VIXLow
        - VIXClose
    output: vix-daily
schedule:
    crontab: '0 0 * * *'
```

Source spec from dashboard http://api.datahub.io/pipelines/#anchor-ALL-core-finance-vix

```
inputs:
- kind: datapackage
  parameters:
    resource-mapping:
      vix-daily: https://s3.amazonaws.com/rawstore.datahub.io/9c46b3948d297fa1c4e92ead714f0399
  url: https://s3.amazonaws.com/rawstore.datahub.io/66387913a43fc2a04ca602ce0d529b1c
meta:
  dataset: finance-vix
  findability: unlisted
  owner: core
  ownerid: core
  update_time: '2017-09-26T10:02:32.931873'
  version: 1
```
